model:
  base_learning_rate: 2e-5
  target: taming.models.vqgan.VQModel
  params:
    num_classes: 5 # ckpt가 5-class 기준으로 학습됨
    ckpt_path: pretrained/stage2.ckpt #null
    stage: 2
    embed_dim: 4
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 192
      in_channels: 1
      out_ch: 1
      ch: 64
      num_groups: 32
      ch_mult:
      - 1
      - 1
      - 2
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 4
        disc_start: 0
        disc_weight: 0.8
        disc_factor: 0
        codebook_weight: 0
        num_classes: 5 # num_class + fake class

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    train:
      target: taming.data.brats.BraTS2021Train
      params:
        data_path: data/BraTS2021/TrainingData
        # csv_path: 
        phase: train
        spatial_size:
        - 128
        - 128
        - 128
    validation:
      target: taming.data.brats.BraTS2021Test
      params:
        data_path: data/BraTS2021/ValidData
        # csv_path: 
        phase: val
        spatial_size:
        - 128
        - 128
        - 128
    test:
      target: taming.data.brats.BraTS2021Test
      params:
        data_path: data/BraTS2021/TestData
        # csv_path: 
        phase: test
        spatial_size:
        - 128
        - 128
        - 128
