model:
  base_learning_rate: 1e-5
  target: taming.models.vqgan.VQModel
  params:
    num_classes: 2
    ckpt_path: null # null
    stage: 1
    embed_dim: 4
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 192
      in_channels: 1
      out_ch: 1
      ch: 64
      num_groups: 32
      ch_mult:
      - 1
      - 1
      - 2
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        # 원래는 싹다 0이었어. disc weight만 0.8이고.
        disc_start: 10000
        disc_weight: 1.0 # 0.8
        disc_factor: 1.0 # 0
        codebook_weight: 0 #0.01 # 1.0 # 0
        perceptual_weight: 1.0 # 0
        cycle_weight: 0.5 # 0
        num_classes: 1

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    train:
      target: taming.data.synthrad.SynthRadTrain
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/train
        phase: train
        spatial_size:
        - 96
        - 96
        - 96
    validation:
      target: taming.data.synthrad.SynthRadVal
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/val
        phase: val
        spatial_size:
        - 96
        - 96
        - 96
    test:
      target: taming.data.synthrad.SynthRadTest
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/test
        phase: test
        spatial_size:
        - 96
        - 96
        - 96
