model:
  base_learning_rate: 1.0e-05
  target: taming.models.vqgan.VQModel
  params:
    num_classes: 2
    ckpt_path: VQ-GAN/pretrained/stage1.ckpt
    stage: 1
    embed_dim: 4
    n_embed: 8192
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 192
      in_channels: 1
      out_ch: 1
      ch: 64
      num_groups: 32
      ch_mult:
      - 1
      - 1
      - 2
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 1
        disc_start: 1000
        disc_weight: 0.8
        disc_factor: 1.0
        codebook_weight: 1.0
        perceptual_weight: 0
        num_classes: 1
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    train:
      target: taming.data.synthrad.SynthRadTrain
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/train
        phase: train
        subject_prefix_mode: all # all|seen|unseen|1PA|1PC|1HNA|1HNC|1HND
        spatial_size:
        - 96
        - 96
        - 96
    validation:
      target: taming.data.synthrad.SynthRadVal
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/val
        phase: val
        subject_prefix_mode: all # all|seen|unseen|1PA|1PC|1HNA|1HNC|1HND
        spatial_size:
        - 96
        - 96
        - 96
    test:
      target: taming.data.synthrad.SynthRadTest
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/test
        phase: test
        subject_prefix_mode: all # all|seen|unseen|1PA|1PC|1HNA|1HNC|1HND
        spatial_size:
        - 96
        - 96
        - 96
