model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: logs/synthrad-ldm-vq-4/Ver2_Stage2Ver1Epo886/2025-12-09T17-33-27/checkpoints/best-epepoch=199-stepstep=11199.ckpt
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: image
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        num_classes: 2
        image_size: 32
        in_channels: 12
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        num_res_blocks: 1
        channel_mult:
        - 1
        - 1
        - 2
        num_head_channels: 32
        transformer_depth: 1
        use_spatial_transformer: false
    first_stage_config:
      target: ldm.models.vqgan.VQModel
      params:
        num_classes: 3
        ckpt_path: logs/synthrad_vqgan_stage2/Ver1_TrainOnAuthorCkptStage1_IgnoreDisc/2025-12-05T00-25-15/checkpoints/best-epepoch=886-stepstep=98456-valrecval_rec_loss=0.0909.ckpt
        stage: 2
        embed_dim: 4
        n_embed: 8192
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 192
          in_channels: 1
          out_ch: 1
          ch: 64
          num_groups: 32
          ch_mult:
          - 1
          - 1
          - 2
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    train:
      target: taming.data.synthrad.SynthRadTrain
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/train
        phase: train
        source: mr
        target: ct
        spatial_size:
        - 128
        - 128
        - 128
        subject_prefix_mode: all
    validation:
      target: taming.data.synthrad.SynthRadVal
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/val
        phase: val
        source: mr
        target: ct
        spatial_size:
        - 128
        - 128
        - 128
        subject_prefix_mode: all
    test:
      target: taming.data.synthrad.SynthRadTest
      params:
        data_path: data/synthrad2023_mr-ct_pelvis/test
        phase: test
        source: mr
        target: ct
        spatial_size:
        - 128
        - 128
        - 128
        subject_prefix_mode: all
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: false
  trainer:
    max_epochs: 200
    check_val_every_n_epoch: 20
inference:
  sliding_window:
    enabled: false
    roi_size:
    - 192
    - 192
    - 192
    overlap: 0.25
    mode: gaussian
    batch_size: 1
    benchmark: true
    disable_foreground_crop: true
    disable_spatial_pad: true
    padding_mode: reflect
    cval: -1.0
